version: "2.6"
services:
  db:
    image: mysql:5.7
    restart: always
    volumes:
      - "./data:/var/lib/mysql:rw"
    environment:
      MYSQL_ROOT_PASSWORD: iris-task
      MYSQL_DATABASE: shop1_development
      MYSQL_USER: appuser
      MYSQL_PASSWORD: iris-task
  appc1: &app_c
    build: ./app
    command: bundle exec rails s -p 3000 -b '0.0.0.0' && rake 
    depends_on:
      - db
    links:
      - db
    environment:
      DB_USER: root
      DB_NAME: shop1_development
      DB_PASSWORD: iris-task
      DB_HOST: db
  appc2:
    <<: *app_c
  appc3:
    <<: *app_c
  web:
    image: nginx
    volumes:
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
    ports:
      - "8080:8080"
    depends_on:
      - appc1
      - appc2
      - appc3
    restart: always
  