version: "2.6"
services:
  db:
    image: mysql:5.7
    restart: always
    volumes:
      - "./data:/var/lib/mysql:rw"
    environment:
      MYSQL_ROOT_PASSWORD: iris-task
      MYSQL_DATABASE: shop1_development
      MYSQL_USER: appuser
      MYSQL_PASSWORD: iris-task
  app:
    build: ./app
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    ports:
      - "8080:3000"
    depends_on:
      - db
    links:
      - db
    environment:
      DB_USER: root
      DB_NAME: shop1_development
      DB_PASSWORD: iris-task
      DB_HOST: db